from django.dispatch import Signal


# when robots.txt data is being generated by the manage.py sync_robots_data
robots_signal = Signal(providing_args=['semester', 'rule'])
sections_modified = Signal(providing_args=['semester'])
